# ==========================================
# 4.2 PUERTO DEL BFF
# ==========================================
server.port=8082

# ==========================================
# CONFIGURACIÓN OAUTH2 / MICROSOFT ENTRA ID
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/3070fad0-b050-48d9-b664-a1cb8ddc6e0a/v2.0

# ==========================================
# 4.3 DIRECCIONES DE LOS MICROSERVICIOS
# ==========================================
# Si estás probando en tu máquina (Localhost):
microservicio.orders.url=http://localhost:8081
microservicio.catalog.url=http://localhost:8083

# NOTA para cuando subas a AWS EC2:
# Cambias "localhost" por la IP interna de Docker o del servidor donde corran los microservicios.